$kind: http-request
method: PUT
url: '{{baseUrl}}/api/applications/{{applicationId}}/status'
order: 7000
headers:
  - key: Authorization
    value: 'Bearer {{authToken}}'
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "status_id": 2
    }
