export { BasicInfoSection } from './_1_BasicInfoSection/basic-info-section';
export { TeamMembersSection } from './_2_TeamMembersSection/team-members-section';
export { CoordinatorsSection } from './_3_CoordinatorsSection/coordinators-section';
export { DobroResponsibleSection } from './_4_DobroResponsibleSection/dobro-responsible-section';
export { ProjectDescriptionSection } from './_5_ProjectDescriptionSection/project-description-section';
export { ProjectPlanSection } from './_6_ProjectPlanSection/project-plan-section';
export { ProjectResultsSection } from './_7_ProjectResultsSection/project-results-section';
export { ProjectBudgetSection } from './_8_ProjectBudgetSection/project-budget-section';
export { AdditionalMaterialsSection } from './_9_AdditionalMaterialsSection/additional-materials-section';
export { TableOfContents } from './TableOfContents';
export type { SectionError } from './TableOfContents';
